services:
  - docker

before_install:
  - docker build -t burningserenity/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run burningserenity/react-test npm test -- --coverage --watchAll=false

after_success:
  - docker build -t burningserenity/multi-client ./client
  - docker build -t burningserenity/multi-nginx ./nginx
  - docker build -t burningserenity/multi-server ./server
  - docker build -t burningserenity/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push burningserenity/multi-client
  - docker push burningserenity/multi-nginx
  - docker push burningserenity/multi-server
  - docker push burningserenity/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "https://s3.console.aws.amazon.com/s3/buckets/elasticbeanstalk-us-east-2-492888762726?region=us-east-2"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
